development:
  adapter: postgresql
  encoding: unicode
  database: event_bright
  pool: 5
  username: tashfeen
  password: gateway123

test:
  adapter: postgresql
  encoding: unicode
  database: event-bright
  pool: 5
  username: tashfeen
  password: gateway123